version: "3.9"
services:
  api:
    container_name: "${APP_NAME}-nodejs"
    build:
      context: .
      dockerfile: Dockerfile
    command: sh ./start.sh
    volumes:
      - .:/usr/src/nodejs
      - storage_api:/usr/src/nodejs/node_modules
    ports:
      - 3333:3333
      - 9229:9229
    networks:
      - default
    depends_on:
      - mysql
  mysql:
    container_name: '${APP_NAME}-mysql'
    image: mysql:5.7.35
    volumes:
      - storage_db:/var/lib/mysql
      #dump dir for production import
      # - ./dump/:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - default
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_ROOT_PASSWORD: 'yes'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
networks:
  default:
    driver: bridge
volumes:
  storage_api:
  storage_db:
